# Default values for jackett.

replicaCount: 1

image:
  repository: lscr.io/linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: "0.22.1211"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

persistence: #currently using the same pvc for config and blackhole directories
  enabled: false  #Enable this to save configuration between restarts
#  existingClaim:  #A k8s PVC that already has been created.
  #If no existingClaim, enabling persistance will create a PVC for you.
#  size:  10G
#  storageClassName: #Storageclass name of the new PVC



#Run a Gluetun container in sidecar mode.
#Gluetun will route all of your Jackett outgoing traffic through a VPN of your choice.
# https://github.com/qdm12/gluetun
gluetun:
  enabled: false
  image:  "ghcr.io/qdm12/gluetun"
  tag: "v3.40.0"
  #vpn_service_provider: "mullvad"
  #vpn_type: "wireguard" #wireguard or openvpn
  #openvpn_user: ""    #Many VPNs, such as Mullvad, just require your secret account number in the user field.
  #openvpn_password: ""
  #openvpn_secret: "" #K8s Secret containing openvpn creds, stored with keys `openvpnuser` and `openvpnpasswd`
  #wireguard_key: ""
  #wireguard_secret: "" #K8s Secret containing wireguard key, stored with keys `wgprivatekey`
  #wireguard_addresses: ""
  #dns_address: "10.64.0.1"
  #provider_extra_env:      #any other env params needed for VPN provider. See documentation https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
  #  - name: SERVER_CITIES
  #    value: "Amsterdam"


service:
  type: ClusterIP
  port: 9117


extraParams: #Additional Params used by Jackett. See https://hub.docker.com/r/linuxserver/jackett/
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "Etc/UTC"
  - name: AUTO_UPDATE
    value: "true"


livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}



ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

additionalVolumes: []  #other than config and downloads
additionalVolumeMounts: []


nodeSelector: {}

tolerations: []

affinity: {}
