apiVersion: v1
kind: Service
metadata:
  name: {{ include "jackett.fullname" . }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9117
      protocol: TCP
      name: http
  selector:
    {{- include "jackett.selectorLabels" . | nindent 4 }}
